// src/constants/languages.ts

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'AF', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'SQ', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'AM', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'AR', name: 'Arabic', nativeName: 'العربية' },
  { code: 'HY', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'AZ', name: 'Azerbaijani', nativeName: 'Azərbaycan' },
  { code: 'EU', name: 'Basque', nativeName: 'Euskara' },
  { code: 'BE', name: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'BN', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'BS', name: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'BG', name: 'Bulgarian', nativeName: 'Български' },
  { code: 'CA', name: 'Catalan', nativeName: 'Català' },
  { code: 'CE', name: 'Cebuano', nativeName: 'Bisaya' },
  { code: 'ZH', name: 'Chinese (Simplified)', nativeName: '简体中文' },
  { code: 'ZH-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文' },
  { code: 'CO', name: 'Corsican', nativeName: 'Corsu' },
  { code: 'HR', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'CS', name: 'Czech', nativeName: 'Čeština' },
  { code: 'DA', name: 'Danish', nativeName: 'Dansk' },
  { code: 'NL', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'EN', name: 'English', nativeName: 'English' },
  { code: 'EO', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'ET', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'FI', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'FR', name: 'French', nativeName: 'Français' },
  { code: 'FY', name: 'Frisian', nativeName: 'Frysk' },
  { code: 'GL', name: 'Galician', nativeName: 'Galego' },
  { code: 'KA', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'DE', name: 'German', nativeName: 'Deutsch' },
  { code: 'EL', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'GU', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'HT', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { code: 'HA', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'HE', name: 'Hebrew', nativeName: 'עברית' },
  { code: 'HI', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'HU', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'IS', name: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'IG', name: 'Igbo', nativeName: 'Igbo' },
  { code: 'ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'GA', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'IT', name: 'Italian', nativeName: 'Italiano' },
  { code: 'JA', name: 'Japanese', nativeName: '日本語' },
  { code: 'JV', name: 'Javanese', nativeName: 'Basa Jawa' },
  { code: 'KN', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'KK', name: 'Kazakh', nativeName: 'Қазақ тілі' },
  { code: 'KM', name: 'Khmer', nativeName: 'ខ្មែរ' },
  { code: 'KO', name: 'Korean', nativeName: '한국어' },
  { code: 'KU', name: 'Kurdish', nativeName: 'Kurdî' },
  { code: 'KY', name: 'Kyrgyz', nativeName: 'Кыргызча' },
  { code: 'LO', name: 'Lao', nativeName: 'ລາວ' },
  { code: 'LA', name: 'Latin', nativeName: 'Latina' },
  { code: 'LV', name: 'Latvian', nativeName: 'Latviešu' },
  { code: 'LT', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { code: 'LB', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'MK', name: 'Macedonian', nativeName: 'Македонски' },
  { code: 'MG', name: 'Malagasy', nativeName: 'Malagasy' },
  { code: 'MS', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'ML', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'MT', name: 'Maltese', nativeName: 'Malti' },
  { code: 'MI', name: 'Maori', nativeName: 'Māori' },
  { code: 'MR', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'MN', name: 'Mongolian', nativeName: 'Монгол' },
  { code: 'NE', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'NO', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'NY', name: 'Nyanja (Chichewa)', nativeName: 'ChiCheŵa' },
  { code: 'PS', name: 'Pashto', nativeName: 'پښتو' },
  { code: 'FA', name: 'Persian', nativeName: 'فارسی' },
  { code: 'PL', name: 'Polish', nativeName: 'Polski' },
  { code: 'PT', name: 'Portuguese', nativeName: 'Português' },
  { code: 'PA', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'RO', name: 'Romanian', nativeName: 'Română' },
  { code: 'RU', name: 'Russian', nativeName: 'Русский' },
  { code: 'SM', name: 'Samoan', nativeName: 'Gagana faʻa Sāmoa' },
  { code: 'GD', name: 'Scots Gaelic', nativeName: 'Gàidhlig' },
  { code: 'SR', name: 'Serbian', nativeName: 'Српски' },
  { code: 'ST', name: 'Sesotho', nativeName: 'Sesotho' },
  { code: 'SN', name: 'Shona', nativeName: 'Chishona' },
  { code: 'SD', name: 'Sindhi', nativeName: 'सिन्धी' },
  { code: 'SI', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'SK', name: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'SL', name: 'Slovenian', nativeName: 'Slovenščina' },
  { code: 'SO', name: 'Somali', nativeName: 'Soomaali' },
  { code: 'ES', name: 'Spanish', nativeName: 'Español' },
  { code: 'SU', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'SW', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'SV', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'TL', name: 'Tagalog (Filipino)', nativeName: 'Wikang Tagalog' },
  { code: 'TG', name: 'Tajik', nativeName: 'Тоҷикӣ' },
  { code: 'TA', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'TE', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'TH', name: 'Thai', nativeName: 'ไทย' },
  { code: 'TR', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'UK', name: 'Ukrainian', nativeName: 'Українська' },
  { code: 'UR', name: 'Urdu', nativeName: 'اردو' },
  { code: 'UZ', name: 'Uzbek', nativeName: 'Oʻzbek' },
  { code: 'VI', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'CY', name: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'XH', name: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'YI', name: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'YO', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'ZU', name: 'Zulu', nativeName: 'isiZulu' },
];
